server:
  port: 8080
  servlet:
    context-path: /api

spring:
  config:
    import: vault://
  cloud:
    vault:
      uri: ${VAULT_URL_PUBLIC:http://localhost:8200}
      token: ${VAULT_TOKEN:root}
      kv:
        backend: secret
        default-context: application

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_JWT_URL:http://localhost:9080/realms/ticket-booking}

app:
  time:
    expiryTime: 3600

keycloak:
  auth-server-url: http://localhost:9080/
  realm: ticket-booking
  resource: booking-app
  credentials:
    id: spring-boot-app
    secret: ${vault.server.keycloak}
  bearer-only: true
  ssl-required: external
  public-client: false
  use-resource-role-mappings: true